# A minimal Supabase CLI config
project_id = "rcpkhtlvfvafympulywx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[analytics]
enabled = false

# Edge Functions Configuration
[functions.list-customers]
verify_jwt = true

[functions.complete-payment]
verify_jwt = false

[functions.confirm-payment]
verify_jwt = false